name: Deploy Github Pages

on:
  push:
    branches: ["*"]

jobs:
  build:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout `master`
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.
      - name: Build and Deploy
        run: |
          npm ci
          npm run build