name: Deploy Github Pages

on:
  push:
    branches: ["*"]

jobs:
  build:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.
      - name: Install and Build
        run: |
          npm ci
          npm run build:prod

  deploy:
    needs: build
    if: success()
    uses: peaceiris/actions-gh-pages@v3
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: dist/zkhiro.github.io
      enable_jekyll: true
