name: Deploy Github Pages

on:
  push:
    branches: ["*"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout master
      uses: actions/checkout@v3
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 18.
    - name: Install and Build
      run: |
        npm ci
        npm run build:prod
        ls
        realpath dist

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/zkhiro.github
        enable_jekyll: true
